config/routes.rb
Homecal::Application.routes.draw do
  resources :bills

  resources :people

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_date :paid_start

  def full_name
    return self.first_name + ' ' + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :ok }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/bills/_form.html.haml
= form_for @bill do |f|
  -if @bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bill.errors.count, "error")} prohibited this bill from being saved:"
      %ul
        - @bill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :group_name
    = f.text_field :group_name
  .field
    = f.label :bill_name
    = f.text_field :bill_name
  .field
    = f.label :due_day
    = f.number_field :due_day
  .field
    = f.label :avg_bill
    = f.text_field :avg_bill
  .actions
    = f.submit 'Save'

app/views/bills/edit.html.haml
%h1 Editing bill

= render 'form'

= link_to 'Show', @bill
\|
= link_to 'Back', bills_path

app/views/bills/index.html.haml
%h1 Listing bills

%table
  %tr
    %th Group name
    %th Bill name
    %th Due day
    %th Avg bill
    %th
    %th
    %th

  - @bills.each do |bill|
    %tr
      %td= bill.group_name
      %td= bill.bill_name
      %td= bill.due_day
      %td= bill.avg_bill
      %td= link_to 'Show', bill
      %td= link_to 'Edit', edit_bill_path(bill)
      %td= link_to 'Destroy', bill, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bill', new_bill_path

app/views/bills/new.html.haml
%h1 New bill

= render 'form'

= link_to 'Back', bills_path

app/views/bills/show.html.haml
%p#notice= notice

%p
  %b Group name:
  = @bill.group_name
%p
  %b Bill name:
  = @bill.bill_name
%p
  %b Due day:
  = @bill.due_day
%p
  %b Avg bill:
  = @bill.avg_bill

= link_to 'Edit', edit_bill_path(@bill)
\|
= link_to 'Back', bills_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homecal</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
%html
%head
  %title Home Calculator
  =stylesheet_link_tag    "application"
  =javascript_include_tag "application"
  =csrf_meta_tags
  %body
  %p This is on every page
  =yield

app/views/people/_form.html.haml
= form_for @person do |f|
  -if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :paid_every
    = f.number_field :paid_every
  .field
    = f.label :paid_interval
    = f.text_field :paid_interval
  .field
    = f.label :paid_start
    = f.text_field :paid_start
  .field
    = f.label :typical_payment
    = f.text_field :typical_payment
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th Name
    %th Paid every
    %th Paid interval
    %th Paid start
    %th Typical payment
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= person.full_name
      %td= person.paid_every
      %td= person.paid_interval
      %td= person.paid_start
      %td= person.typical_payment
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @person.first_name
%p
  %b Last name:
  = @person.last_name
%p
  %b Paid every:
  = @person.paid_every
%p
  %b Paid interval:
  = @person.paid_interval
%p
  %b Paid start:
  = @person.paid_start
%p
  %b Typical payment:
  = @person.typical_payment

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path